baseURL = ''
languageCode = 'en-us'
title = 'the broader things'
theme = "terminal"
pagination.pagerSize = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 7

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "updated"

  # whether to show a page's estimated reading time
  readingTime = true # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  TocTitle = "contents" # default

[languages]
  [languages.en]
    languageName = "English"
    title = "the broader things"

    [languages.en.params]
      subtitle = "knowledge without action is a missed opportunity"
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "the broader things"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "about"
          url = "/about"
          weight = 10
        [[languages.en.menu.main]]
          identifier = "projects"
          name = "projects"
          url = "/projects"
          weight = 20
        [[languages.en.menu.main]]
          identifier = "posts"
          name = "posts"
          url = "/posts"
          weight = 30
        [[languages.en.menu.main]]
          identifier = "tags"
          name = "tags"
          url = "/tags"
          weight = 40
        [[languages.en.menu.main]]
          identifier = "github"
          name = "github"
          url = "https://github.com/dotsdl"
        [[languages.en.menu.main]]
          identifier = "linkedin"
          name = "linkedin"
          url = "https://www.linkedin.com/in/dotsdl/"
        [[languages.en.menu.main]]
          identifier = "orcid"
          name = "orcid"
          url = "https://orcid.org/0000-0001-5879-2942"
